export const resultModalStyles = {
  backdrop: 'flex-1 items-center justify-center bg-black/50',
  card: 'w-11/12 max-w-sm rounded-2xl bg-white dark:bg-gray-800 p-6',
  headline: 'text-2xl font-bold text-center mb-4 text-black dark:text-white',
  statsRow: 'flex-row justify-between mb-4',
  statItem: 'items-center',
  statValue: 'text-2xl font-bold text-black dark:text-white',
  statLabel: 'text-xs text-gray-500 dark:text-gray-400',
  distribution: 'mb-4',
  distributionRow: 'flex-row items-center mb-1',
  distributionLabel: 'w-4 text-xs text-black dark:text-white',
  distributionBar: 'bg-green-600 rounded-md justify-end px-1 min-h-[18px]',
  distributionCount: 'text-white text-xs font-semibold',
  shareButton: 'bg-green-600 rounded-xl py-3 items-center',
  shareButtonText: 'text-white font-bold',
};
